<a href="https://colab.research.google.com/github/jubymariajoseph/DSA-Activities/blob/main/numpy%26pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Numpy assignment

In [ ]:
#1.create a numpy array with values from 10 to 49 (inclusive).
#● Reshape it into a 4x10 matrix.extract the last column from the reshaped matrix
import numpy as np
a1 = np.arange(10,50)
print(a1)
print(a1.shape)
a12 = np.reshape(a1,(4,10))
print("the reshaped array\n",a12)
print("The last column\n",a12[:,-1:])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
(40,)
the reshaped array
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
The last column
 [[19]
 [29]
 [39]
 [49]]


In [ ]:
#2.Create two 3×3 matrices: One filled with all 5s , One with values from 1 to 9
#● Add the two matrices ● Multiply them element-wise ● Then find the transpose of the result
a21 = np.array([[5,5,5],[5,5,5],[5,5,5]])
a22 = np.arange(1,10)
a23 = np.reshape(a22,(3,3))
print("array one\n",a21)
print("array 2\n",a23)
sum = np.add(a21, a23)
print("Added value\n",sum)
print("Product\n",a21*a23)
print("Transpose is\n",(a21*a23).T)

array one
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
array 2
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Added value
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Product
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transpose is
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [ ]:
#3.Create a NumPy array of 15 random integers between 10 and 100.
#● Replace all values greater than 50 with -1 ● Count how many values were replaced.
a3 = np.random.randint(10,100,size=(5,3))
a31 = []
count=0
print("The array is\n",a3)
flat_a3 = a3.flatten()
for i in range(15):
  if flat_a3[i]>50:
    a31.append(-1)
    count+=1
  else:
    a31.append(flat_a3[i])
a31 = np.reshape(a31,(5, 3))
print("replaced\n",a31)
print("count is ",count)

The array is
 [[53 74 95]
 [27 10 26]
 [94 50 59]
 [68 28 54]
 [16 41 11]]
replaced
 [[-1 -1 -1]
 [27 10 26]
 [-1 50 -1]
 [-1 28 -1]
 [16 41 11]]
count is  7


In [88]:
#4.Generate a 5×4 array with random values between 0 and 1 (float).
#● Find the row with the maximum sum of values. ● Normalize each row using the formula:x-min/(max-min)
a4 = np.random.random((5, 4))
print("The array is\n", a4)
sum4 = np.sum(a4, axis=1)
print("Sum of rows:", sum4)
row_index = np.argmax(sum4)
print("The row with maximum sum is:", a4[row_index])
min_vals = a4.min(axis=1).reshape(-1,1)  # min of each row as column vector
max_vals = a4.max(axis=1).reshape(-1,1)  # max of each row as column vector

a4_norm = (a4 - min_vals)/(max_vals-min_vals)
print("Normalized array:\n",a4_norm)


The array is
 [[0.11722452 0.20531604 0.51004341 0.25584668]
 [0.21593669 0.21433919 0.23265509 0.36330522]
 [0.37225521 0.91280345 0.17109009 0.61022362]
 [0.19450402 0.94114394 0.02108276 0.26097229]
 [0.2489312  0.25204313 0.93902309 0.8773496 ]]
Sum of rows: [1.08843065 1.02623619 2.06637236 1.41770301 2.31734703]
The row with maximum sum is: [0.2489312  0.25204313 0.93902309 0.8773496 ]
Normalized array:
 [[0.         0.22425481 1.         0.35289076]
 [0.01072393 0.         0.12295354 1.        ]
 [0.27121679 1.         0.         0.59205288]
 [0.18848884 1.         0.         0.26073215]
 [0.         0.00450945 1.         0.91063003]]


In [ ]:
#5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
#● Find all unique elements ● Find the duplicates (elements that appear more than once)
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements, counts = np.unique(arr, return_counts=True)
unique = unique_elements[counts==1]
print("All unique elements:",unique)
duplicates = unique_elements[counts>1]
print("Duplicate elements:",duplicates)

All unique elements: [7 9]
Duplicate elements: [1 3 5]


In [ ]:
#6.Create a 6×6 NumPy array with values from 1 to 36.
#● Extract the middle 4×4 submatrix. ● Then extract all even numbers from this submatrix.
a6 = np.random.randint(1,37,size=(6,6))
print("The array\n",a6)
a61=a6[1:5,1:5]
print("submatrix\n",a61)
a62=a61[a61%2==0]
print("Even numbers:",a62)

The array
 [[21 17  4 36  5 30]
 [18 25  2 27 28 22]
 [18 34  9 31 26  8]
 [ 3 13  3 36 13 16]
 [ 9 34 27 21  1 22]
 [ 2  7 28 27 20 22]]
submatrix
 [[25  2 27 28]
 [34  9 31 26]
 [13  3 36 13]
 [34 27 21  1]]
Even numbers: [ 2 28 34 26 36 34]


In [ ]:
#7.Generate an array of shape (3, 4) with values from 0 to 11.
#● Reshape it to (2, 6) ● Then flatten it into a 1D array ● Convert the 1D array back to shape (4, 3)
a7 = np.random.randint(0,11,size=(3,4))
print("the matrix\n",a7)
a71=np.reshape(a7,(2,6))
print("the reshaped\n",a71)
a72=a71.flatten()
print("flattened:",a72)
a73=np.reshape(a72,(4,3))
print("the reshaped\n",a73)

the matrix
 [[ 2 10  5  1]
 [ 8  8 10  0]
 [ 8  8  7  4]]
the reshaped
 [[ 2 10  5  1  8  8]
 [10  0  8  8  7  4]]
flattened: [ 2 10  5  1  8  8 10  0  8  8  7  4]
the reshaped
 [[ 2 10  5]
 [ 1  8  8]
 [10  0  8]
 [ 8  7  4]]


In [ ]:
#Create an array: a = np.array([[1, 2], [3, 4]])
#● Append a new row [5, 6] ● Then append a new column [7, 8, 9]
a = np.array([[1, 2], [3, 4]])
row = np.array([[5, 6]])
result = np.append(a,row,axis=0)
print("row appended\n",result)
column = np.array([[7],[8],[9]])
result1 = np.append(result,column,axis=1)
print("column appended\n",result1)

row appended
 [[1 2]
 [3 4]
 [5 6]]
column appended
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
#a = np.array([1, 2, 3]) b = np.array([4, 5, 6]) c = np.array([7, 8, 9])
#● Join them into a single array ● Reshape the result into a 3×3 matrix ● Extract the diagonal elements
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
s=np.concatenate((a,b,c))
print("single array:",s)
s1=np.reshape(s,(3,3))
print("reshaped\n",s1)
diag = np.diagonal(s1)
print("Main diagonal:", diag)

single array: [1 2 3 4 5 6 7 8 9]
reshaped
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Main diagonal: [1 5 9]


In [ ]:
#Create a NumPy array of integers from 1 to 20.
#● Extract all values that are divisible by 3 or 5. ● Count how many such values exist.
a9 = np.random.randint(1,21,size=(4,5))
a91 = []
count1=0
print("The array is\n",a9)
flat_a9 = a9.flatten()
for i in flat_a9:
  if i%3==0 or i%5==0:
    a91.append(int(i))
    count1+=1
print("the numbers:\n",a91)
print("count is ",count1)

The array is
 [[20 19 16  1 11]
 [10 14  6 17 12]
 [14 13 19 18 13]
 [ 8 18  1 15 18]]
the numbers:
 [20, 10, 6, 12, 18, 18, 15, 18]
count is  8


Pandas activity

In [59]:
#1.Load the Titanic dataset and display the first 10 rows.
import pandas as pd
import seaborn as sns
data = sns.load_dataset('titanic')
df=pd.DataFrame(data)
print(df.head(10))

   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes

In [60]:
#2. Find the number of missing values in each column.
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [62]:
#3. Find the percentage of passengers who survived, grouped by gender.
df.groupby('sex')['survived'].mean()*100

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

In [64]:
#4. Find the average, median, and standard deviation of passenger ages.
print("Average",df["age"].mean())
print("Median",df["age"].median())
print("Standard deviation",df["age"].std())

Average 29.69911764705882
Median 28.0
Standard deviation 14.526497332334044


In [65]:
#5.Count how many passengers were in each class (pclass).
df['pclass'].value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [66]:
#6. Show all passengers who were female, under age 18, and survived.
df[(df['sex']<="female") & (df['age']<=18) & (df['survived']==1)]

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
311         1       1  female  18.00      2      2  262.3750        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
417         1       2  female  18.00      0      2   13.0000        S  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
585         1       1  female  18.00      0      2   79.6500        S   First   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
651         1       2  female  18.00      0      1   23.0000        S  Second   
677         1       3  female  18.00      0      0    9.8417        S   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
700         1       1  female  18.00      1      0  227.5250        C   First   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
786         1       3  female  18.00      0      0    7.4958        S   Third   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
855         1       3  female  18.00      0      1    9.3500        S   Third   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN  

In [70]:
#7. Replace missing age values with the median age.
print(df['age'].fillna(df['age'].median()))
print(df.isnull().sum())

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64
survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


In [73]:
#8.Create a column age_group with values:
#a. 'Child' for age < 18 b. 'Adult' for age 18–60 c. 'Senior' for age > 60 d. Use: apply() or np.where() or custom function
def classify_age(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['age'].apply(classify_age)
print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone age_group  
0    man        True  NaN  Southampton    no  False     Adult  
1  woman       False    C    Cherbourg   yes  False     Adult  
2  woman       False  NaN  Southampton   yes   True     Adult  
3  woman       False    C  Southampton   yes  False     Adult  
4    man        True  NaN  Southampton    no   True     Adult  


In [74]:
#9.Display the top 5 passengers who paid the highest fare.
top_fare = df.sort_values(by='fare',ascending=False).head(5)
print(top_fare)


     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
679    man        True    B    Cherbourg   yes  False     Adult  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
88   woman       False    C  Southampton   yes  False     Adult  
438    man        True    C  Southampton    no  False    Senior  


In [76]:
#10. Find the average fare paid, grouped by both pclass and sex.
df.groupby(['sex','pclass'])['fare'].mean()

sex     pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: fare, dtype: float64

In [85]:
#11.Rename the following columns:
#a. 'sex' → 'gender' b. 'fare' → 'ticket_fare'
df=df.rename(columns={'sex': 'gender', 'fare': 'ticket_fare'})
print(df.head())

   survived  pclass  gender   age  sibsp  parch  ticket_fare embarked  class  \
0         0       3    male  22.0      1      0       7.2500        S  Third   
1         1       1  female  38.0      1      0      71.2833        C  First   
2         1       3  female  26.0      0      0       7.9250        S  Third   
3         1       1  female  35.0      1      0      53.1000        S  First   
4         0       3    male  35.0      0      0       8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone age_group  
0    man        True  NaN  Southampton    no  False     Adult  
1  woman       False    C    Cherbourg   yes  False     Adult  
2  woman       False  NaN  Southampton   yes   True     Adult  
3  woman       False    C  Southampton   yes  False     Adult  
4    man        True  NaN  Southampton    no   True     Adult  


In [78]:
#12.Count the number of passengers who survived and didn’t survive, grouped by class.
df.groupby('class')['survived'].value_counts()

/tmp/ipython-input-3563193797.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('class')['survived'].value_counts()


class   survived
First   1           136
        0            80
Second  0            97
        1            87
Third   0           372
        1           119
Name: count, dtype: int64

In [87]:
#13. Find the average age of passengers grouped by both class and gender.

df.groupby(['class','gender'])['age'].mean()

/tmp/ipython-input-406900579.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['class','gender'])['age'].mean()


class   gender
First   female    33.978723
        male      38.995246
Second  female    28.703947
        male      30.512315
Third   female    23.572917
        male      26.911873
Name: age, dtype: float64